groups:
  - name: sag-rag-alerts
    rules:
      - alert: HighRequestLatency
        expr: sum(rate(sag_rag_request_latency_ms_total[5m])) / sum(rate(sag_rag_requests_total[5m])) > 2000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency"
      - alert: HighErrorRate
        expr: sum(rate(sag_rag_requests_total{status=~"5.."}[5m])) / sum(rate(sag_rag_requests_total[5m])) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx error rate"
